import React, { ReactNode } from "react";
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/layout/theme-provider";
import { ToasterProvider } from "@/components/layout/toaster-provider";
import Providers from "@/app/providers";
import { ModeToggle } from "@/components/elements/mode-toggle";
import { QuickSetting } from "@/components/elements/quick-setting";
import { appGlobal } from "@/constants/constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: appGlobal.name,
  description: appGlobal.description,
  // description: "Generated by create next app", add cloudflare
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            {/* <QuickSetting
              className="absolute top-5 right-5"
            />
            <ModeToggle
              className="absolute top-5 right-5"
            /> */}
            <ToasterProvider />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
